require './app'
require './controllers/simple'
require './controllers/color'
require './controllers/css'
require './controllers/centrality'
require './controllers/community'
require './controllers/text-cutoff'
require './controllers/ui'
